name: twitter_api_v2
description: The lightweight and powerful wrapper library for Twitter API v2.0 written in Dart language. It works cross-platform.
version: 4.1.2
repository: https://github.com/twitter-dart/twitter-api-v2
issue_tracker: https://github.com/twitter-dart/twitter-api-v2/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  twitter_api_core: ^1.3.4
  http: ^0.13.5
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  freezed: ^2.1.1
  import_sorter: ^4.6.0
  mockito: ^5.3.2
