name: twitter_api_v2
description: The most famous and powerful Dart/Flutter library for Twitter API v2.0.
version: 4.9.3
repository: https://github.com/twitter-dart/twitter-api-v2
issue_tracker: https://github.com/twitter-dart/twitter-api-v2/issues
homepage: https://github.com/twitter-dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.5
  mime: ^1.0.4
  oauth1: ^2.0.0
  universal_io: ^2.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  mockito: ^5.3.2

import_sorter:
  emojis: true
