name: twitter_api_v2
description: The lightweight and powerful wrapper library for Twitter API v2.0 written in Dart language. It works cross-platform.
version: 3.1.0
repository: https://github.com/twitter-dart/twitter-api-v2
issue_tracker: https://github.com/twitter-dart/twitter-api-v2/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  twitter_api_core: ^0.0.10
  http: ^0.13.5
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.5
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0
  mockito: ^5.3.0
