name: Response to opened PR

on:
  pull_request:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: do not merge yet

  self_assign:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - name: self assign
      env:
        ASSIGNEES: "${{ github.actor }}"
      run: |
        assignee_count=$(cat ${{ github.event_path }} | jq '.pull_request.assignees | length')
        if [[ 0 == $assignee_count ]]; then
          assignees=$(echo "\"${ASSIGNEES// /}\"" | jq 'split(",")')
          curl -X POST \
                -H "Content-Type: application/json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -d "{ \"assignees\": $assignees }" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees
        fi
