name: Response to reviewed PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-state:
    if: github.event.review.state != 'approved' && github.event.pull_request.base.ref == 'main' && ${{ startsWith(github.event.comment.body, 'passed') }}
    runs-on: ubuntu-latest
    steps:
      - name: Find last comment
        id: find-last-comment
        uses: peter-evans/find-comment@v2
        with:
          issue-number: ${{github.event.pull_request.number}}
          comment-author: 'github-actions[bot]'
          body-includes: 'Congratulations, this pull request has been reviewed and is ready for merging!'

      - name: Comment
        if: steps.find-last-comment.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: 'Congratulations, this pull request has been reviewed and is ready for merging!'

  remove_label:
    if: github.event.review.state != 'approved' && github.event.pull_request.base.ref == 'main' && ${{ startsWith(github.event.comment.body, 'pass') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: do not merge yet
