# TODO: If https://github.com/dependabot/dependabot-core/issues/2166 has been resolved, this workflow becomes unnecessary.

name: Upgrade Dart Dependencies

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  upgrade_dart_dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: dart-lang/setup-dart@v1
      - run: dart pub upgrade --null-safety # See: https://dart.dev/tools/pub/cmd/pub-upgrade#--null-safety

      # See: https://github.com/peter-evans/create-pull-request/tree/master#reference-example
      - name: create PR
        uses: peter-evans/create-pull-request@v4
        with:
          # See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          # See: https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-537478081
          token: ${{ secrets.PAT }}
          # See: https://github.com/peter-evans/create-pull-request/issues/593
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: '[Scheduled] `dart pub upgrade --null-safety`'
          title: '[Scheduled] `dart pub upgrade --null-safety`'
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
            ---
            See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs
          branch: cron_upgrade_dart_dependencies
          delete-branch: true
          labels: GitHub Actions
          assignees: myConsciousness
          reviewers: myConsciousness
